/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as FeeCollectorPerTokenPairImplContractJson } from "../examples/FeeCollectorPerTokenPairImpl.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace FeeCollectorPerTokenPairImplTypes {
  export type Fields = {
    tokenPairFactory: HexString;
    tokenPair: HexString;
  };

  export type State = ContractState<Fields>;
}

class Factory extends ContractFactory<
  FeeCollectorPerTokenPairImplInstance,
  FeeCollectorPerTokenPairImplTypes.Fields
> {
  encodeFields(fields: FeeCollectorPerTokenPairImplTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as FeeCollectorPerTokenPairImplTypes.Fields;
  }

  consts = { ErrorCodes: { InvalidCaller: BigInt(16) } };

  at(address: string): FeeCollectorPerTokenPairImplInstance {
    return new FeeCollectorPerTokenPairImplInstance(address);
  }

  tests = {
    collectFee: async (
      params: TestContractParamsWithoutMaps<
        FeeCollectorPerTokenPairImplTypes.Fields,
        { from: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "collectFee", params);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        FeeCollectorPerTokenPairImplTypes.Fields,
        { to: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params);
    },
    destroy: async (
      params: TestContractParamsWithoutMaps<
        FeeCollectorPerTokenPairImplTypes.Fields,
        { to: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "destroy", params);
    },
    collectFeeManually: async (
      params: Omit<
        TestContractParamsWithoutMaps<
          FeeCollectorPerTokenPairImplTypes.Fields,
          never
        >,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "collectFeeManually", params);
    },
  };
}

// Use this object to test and deploy the contract
export const FeeCollectorPerTokenPairImpl = new Factory(
  Contract.fromJson(
    FeeCollectorPerTokenPairImplContractJson,
    "",
    "854934781b951bef0fe2035d06ef61bc11021157d31f464ac25364f5ef600c53",
    []
  )
);

// Use this class to interact with the blockchain
export class FeeCollectorPerTokenPairImplInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FeeCollectorPerTokenPairImplTypes.State> {
    return fetchContractState(FeeCollectorPerTokenPairImpl, this);
  }
}
