/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as TokenBContractJson } from "../examples/TokenB.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace TokenBTypes {
  export type Fields = {
    symbol: HexString;
    name: HexString;
    decimals: bigint;
    supply: bigint;
    balance: bigint;
  };

  export type State = ContractState<Fields>;

  export type WithdrawEvent = ContractEvent<{ to: Address; amount: bigint }>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    balance: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    withdraw: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getSymbol: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDecimals: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    balance: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<TokenBInstance, TokenBTypes.Fields> {
  encodeFields(fields: TokenBTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Withdraw: 0 };
  consts = { ErrorCodes: { InvalidWithdrawAmount: BigInt("0") } };

  at(address: string): TokenBInstance {
    return new TokenBInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParamsWithoutMaps<TokenBTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSymbol", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<TokenBTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDecimals: async (
      params: Omit<
        TestContractParamsWithoutMaps<TokenBTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDecimals", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<TokenBTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
    balance: async (
      params: Omit<
        TestContractParamsWithoutMaps<TokenBTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "balance", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        TokenBTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: TokenBTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const TokenB = new Factory(
  Contract.fromJson(
    TokenBContractJson,
    "=20-2+7a=111-1+4=10+a0007e02175468652063757272656e742062616c616e63652069732000=64",
    "ccaaa416df536a80a2ad67d961654823d45740b70e99e7e6e07473d8efaddddd",
    []
  )
);

// Use this class to interact with the blockchain
export class TokenBInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TokenBTypes.State> {
    return fetchContractState(TokenB, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeWithdrawEvent(
    options: EventSubscribeOptions<TokenBTypes.WithdrawEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TokenB.contract,
      this,
      options,
      "Withdraw",
      fromCount
    );
  }

  view = {
    getSymbol: async (
      params?: TokenBTypes.CallMethodParams<"getSymbol">
    ): Promise<TokenBTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        TokenB,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: TokenBTypes.CallMethodParams<"getName">
    ): Promise<TokenBTypes.CallMethodResult<"getName">> => {
      return callMethod(
        TokenB,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: TokenBTypes.CallMethodParams<"getDecimals">
    ): Promise<TokenBTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        TokenB,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: TokenBTypes.CallMethodParams<"getTotalSupply">
    ): Promise<TokenBTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        TokenB,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    balance: async (
      params?: TokenBTypes.CallMethodParams<"balance">
    ): Promise<TokenBTypes.CallMethodResult<"balance">> => {
      return callMethod(
        TokenB,
        this,
        "balance",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: TokenBTypes.CallMethodParams<"withdraw">
    ): Promise<TokenBTypes.CallMethodResult<"withdraw">> => {
      return callMethod(
        TokenB,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getSymbol: async (
      params: TokenBTypes.SignExecuteMethodParams<"getSymbol">
    ): Promise<TokenBTypes.SignExecuteMethodResult<"getSymbol">> => {
      return signExecuteMethod(TokenB, this, "getSymbol", params);
    },
    getName: async (
      params: TokenBTypes.SignExecuteMethodParams<"getName">
    ): Promise<TokenBTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(TokenB, this, "getName", params);
    },
    getDecimals: async (
      params: TokenBTypes.SignExecuteMethodParams<"getDecimals">
    ): Promise<TokenBTypes.SignExecuteMethodResult<"getDecimals">> => {
      return signExecuteMethod(TokenB, this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: TokenBTypes.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<TokenBTypes.SignExecuteMethodResult<"getTotalSupply">> => {
      return signExecuteMethod(TokenB, this, "getTotalSupply", params);
    },
    balance: async (
      params: TokenBTypes.SignExecuteMethodParams<"balance">
    ): Promise<TokenBTypes.SignExecuteMethodResult<"balance">> => {
      return signExecuteMethod(TokenB, this, "balance", params);
    },
    withdraw: async (
      params: TokenBTypes.SignExecuteMethodParams<"withdraw">
    ): Promise<TokenBTypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(TokenB, this, "withdraw", params);
    },
  };

  async multicall<Callss extends TokenBTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<TokenBTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      TokenB,
      this,
      callss,
      getContractByCodeHash
    )) as TokenBTypes.MulticallReturnType<Callss>;
  }
}
