/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as TokenAContractJson } from "../examples/TokenA.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace TokenATypes {
  export type Fields = {
    symbol: HexString;
    name: HexString;
    decimals: bigint;
    supply: bigint;
    balance: bigint;
  };

  export type State = ContractState<Fields>;

  export type WithdrawEvent = ContractEvent<{ to: Address; amount: bigint }>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    balance: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    withdraw: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getSymbol: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDecimals: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    balance: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<TokenAInstance, TokenATypes.Fields> {
  encodeFields(fields: TokenATypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Withdraw: 0 };
  consts = { ErrorCodes: { InvalidWithdrawAmount: BigInt("0") } };

  at(address: string): TokenAInstance {
    return new TokenAInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParamsWithoutMaps<TokenATypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSymbol", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<TokenATypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDecimals: async (
      params: Omit<
        TestContractParamsWithoutMaps<TokenATypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDecimals", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<TokenATypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
    balance: async (
      params: Omit<
        TestContractParamsWithoutMaps<TokenATypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "balance", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        TokenATypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: TokenATypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const TokenA = new Factory(
  Contract.fromJson(
    TokenAContractJson,
    "=20-2+7a=111-1+4=10+a0007e02175468652063757272656e742062616c616e63652069732000=64",
    "ccaaa416df536a80a2ad67d961654823d45740b70e99e7e6e07473d8efaddddd",
    []
  )
);

// Use this class to interact with the blockchain
export class TokenAInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TokenATypes.State> {
    return fetchContractState(TokenA, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeWithdrawEvent(
    options: EventSubscribeOptions<TokenATypes.WithdrawEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TokenA.contract,
      this,
      options,
      "Withdraw",
      fromCount
    );
  }

  view = {
    getSymbol: async (
      params?: TokenATypes.CallMethodParams<"getSymbol">
    ): Promise<TokenATypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        TokenA,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: TokenATypes.CallMethodParams<"getName">
    ): Promise<TokenATypes.CallMethodResult<"getName">> => {
      return callMethod(
        TokenA,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: TokenATypes.CallMethodParams<"getDecimals">
    ): Promise<TokenATypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        TokenA,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: TokenATypes.CallMethodParams<"getTotalSupply">
    ): Promise<TokenATypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        TokenA,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    balance: async (
      params?: TokenATypes.CallMethodParams<"balance">
    ): Promise<TokenATypes.CallMethodResult<"balance">> => {
      return callMethod(
        TokenA,
        this,
        "balance",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: TokenATypes.CallMethodParams<"withdraw">
    ): Promise<TokenATypes.CallMethodResult<"withdraw">> => {
      return callMethod(
        TokenA,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getSymbol: async (
      params: TokenATypes.SignExecuteMethodParams<"getSymbol">
    ): Promise<TokenATypes.SignExecuteMethodResult<"getSymbol">> => {
      return signExecuteMethod(TokenA, this, "getSymbol", params);
    },
    getName: async (
      params: TokenATypes.SignExecuteMethodParams<"getName">
    ): Promise<TokenATypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(TokenA, this, "getName", params);
    },
    getDecimals: async (
      params: TokenATypes.SignExecuteMethodParams<"getDecimals">
    ): Promise<TokenATypes.SignExecuteMethodResult<"getDecimals">> => {
      return signExecuteMethod(TokenA, this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: TokenATypes.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<TokenATypes.SignExecuteMethodResult<"getTotalSupply">> => {
      return signExecuteMethod(TokenA, this, "getTotalSupply", params);
    },
    balance: async (
      params: TokenATypes.SignExecuteMethodParams<"balance">
    ): Promise<TokenATypes.SignExecuteMethodResult<"balance">> => {
      return signExecuteMethod(TokenA, this, "balance", params);
    },
    withdraw: async (
      params: TokenATypes.SignExecuteMethodParams<"withdraw">
    ): Promise<TokenATypes.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(TokenA, this, "withdraw", params);
    },
  };

  async multicall<Callss extends TokenATypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<TokenATypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      TokenA,
      this,
      callss,
      getContractByCodeHash
    )) as TokenATypes.MulticallReturnType<Callss>;
  }
}
